/*
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
*/

var sum = 0, num = 1, oldNum = 1

while num < Int(4e6) {
	sum += num % 2 == 0 ? num : 0
	(oldNum, num) = (num, num+oldNum)
}

println(sum)
